# This is the reference pipeline configuration file.

# The name of the pipeline is used for logging and reporting purposes
[pipe]
name = "noop"

# The source section defines the start of the pipeline. A source processor generates batches of messages
# that are sent down the pipe. Only one source is permitted and is required. This example uses the 'kafka'
# plugin. Consult the documentation for the option for this plugin
[source]
plugin = "noop"

# if a conduit is named in any other processors destination, it is an error for them to have source set to true
# a conduit may only send to conduits that are named after it. Sending to an earlier defined conduit produces
# a warning and the value will be ignored.
# A conduit with no valid destination specified will be connected to the sink
# The last conduit named is automatically conected to the sink
# The first named conduit is automcatically connected to the source
[[conduit]]
plugin = "noop"
option_one = "fizz"
option_two = "buz"

[sink.accept]
plugin = "noop"
bar = 2

[sink.reject]
plugin = "noop"
option_one = "fizz"
option_two = "buzz"
