// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Priority             uint32               `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Received             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=received,proto3" json:"received,omitempty"`
	Body                 *_struct.Struct      `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_16df6c5bf0e27742, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Message) GetReceived() *timestamp.Timestamp {
	if m != nil {
		return m.Received
	}
	return nil
}

func (m *Message) GetBody() *_struct.Struct {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "core.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_16df6c5bf0e27742) }

var fileDescriptor_message_16df6c5bf0e27742 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0xce, 0x2f, 0x4a, 0x95,
	0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0x97, 0x64,
	0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x94, 0x49, 0xc9, 0xa0, 0x2b, 0x28, 0x2e, 0x29,
	0x2a, 0x4d, 0x2e, 0x81, 0xc8, 0x2a, 0x75, 0x31, 0x72, 0xb1, 0xfb, 0x42, 0x8c, 0x15, 0x92, 0xe2,
	0xe2, 0x28, 0x28, 0xca, 0xcc, 0x2f, 0xca, 0x2c, 0xa9, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d,
	0x82, 0xf3, 0x85, 0xcc, 0xb8, 0x38, 0x8a, 0x52, 0x93, 0x53, 0x33, 0xcb, 0x52, 0x53, 0x24, 0x98,
	0x14, 0x18, 0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x20, 0x06, 0xeb, 0xc1, 0x0c, 0xd6, 0x0b, 0x81, 0xd9,
	0x1c, 0x04, 0x57, 0x2b, 0xa4, 0xcd, 0xc5, 0x92, 0x94, 0x9f, 0x52, 0x29, 0xc1, 0x0c, 0xd6, 0x23,
	0x8e, 0xa1, 0x27, 0x18, 0xec, 0x98, 0x20, 0xb0, 0xa2, 0x24, 0x36, 0xb0, 0xb0, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x51, 0xa0, 0xba, 0x1e, 0xe9, 0x00, 0x00, 0x00,
}
