// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Priority int32

const (
	Message_URGENT Message_Priority = 0
	Message_HIGH   Message_Priority = 1
	Message_NORMAL Message_Priority = 2
	Message_LOW    Message_Priority = 3
)

var Message_Priority_name = map[int32]string{
	0: "URGENT",
	1: "HIGH",
	2: "NORMAL",
	3: "LOW",
}
var Message_Priority_value = map[string]int32{
	"URGENT": 0,
	"HIGH":   1,
	"NORMAL": 2,
	"LOW":    3,
}

func (x Message_Priority) String() string {
	return proto.EnumName(Message_Priority_name, int32(x))
}
func (Message_Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_bde287ef9c1617fa, []int{0, 0}
}

type Message struct {
	Priority             Message_Priority     `protobuf:"varint,1,opt,name=priority,proto3,enum=message.Message_Priority" json:"priority,omitempty"`
	Received             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=received,proto3" json:"received,omitempty"`
	Body                 *any.Any             `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_bde287ef9c1617fa, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetPriority() Message_Priority {
	if m != nil {
		return m.Priority
	}
	return Message_URGENT
}

func (m *Message) GetReceived() *timestamp.Timestamp {
	if m != nil {
		return m.Received
	}
	return nil
}

func (m *Message) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterEnum("message.Message_Priority", Message_Priority_name, Message_Priority_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_bde287ef9c1617fa) }

var fileDescriptor_message_bde287ef9c1617fa = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0xa5, 0xe4, 0xd3,
	0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xc2, 0x49, 0xa5, 0x69, 0xfa, 0x25, 0x99, 0xb9, 0xa9,
	0xc5, 0x25, 0x89, 0xb9, 0x05, 0x10, 0x95, 0x52, 0x92, 0xe8, 0x0a, 0x12, 0xf3, 0x2a, 0x21, 0x52,
	0x4a, 0x37, 0x19, 0xb9, 0xd8, 0x7d, 0x21, 0xe6, 0x08, 0x99, 0x72, 0x71, 0x14, 0x14, 0x65, 0xe6,
	0x17, 0x65, 0x96, 0x54, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x49, 0xea, 0xc1, 0xac, 0x84,
	0xaa, 0xd1, 0x0b, 0x80, 0x2a, 0x08, 0x82, 0x2b, 0x15, 0x32, 0xe3, 0xe2, 0x28, 0x4a, 0x4d, 0x4e,
	0xcd, 0x2c, 0x4b, 0x4d, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0x58, 0xa8,
	0x07, 0xb3, 0x50, 0x2f, 0x04, 0xe6, 0xa2, 0x20, 0xb8, 0x5a, 0x21, 0x0d, 0x2e, 0x96, 0xa4, 0xfc,
	0x94, 0x4a, 0x09, 0x66, 0xb0, 0x1e, 0x11, 0x0c, 0x3d, 0x8e, 0x79, 0x95, 0x41, 0x60, 0x15, 0x4a,
	0xa6, 0x5c, 0x1c, 0x30, 0x7b, 0x85, 0xb8, 0xb8, 0xd8, 0x42, 0x83, 0xdc, 0x5d, 0xfd, 0x42, 0x04,
	0x18, 0x84, 0x38, 0xb8, 0x58, 0x3c, 0x3c, 0xdd, 0x3d, 0x04, 0x18, 0x41, 0xa2, 0x7e, 0xfe, 0x41,
	0xbe, 0x8e, 0x3e, 0x02, 0x4c, 0x42, 0xec, 0x5c, 0xcc, 0x3e, 0xfe, 0xe1, 0x02, 0xcc, 0x49, 0x6c,
	0x60, 0xa3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x54, 0x38, 0x56, 0xd5, 0x38, 0x01, 0x00,
	0x00,
}
